<?xml version="1.0" encoding="UTF-8"?>


<quiz>
   
<question>
<ques><p>What does it mean to say
that a program is <i>robust</i>?</p>
</ques>
<ans><p>A robust program is one that can
handle errors and other unexpected conditions in some reasonable way. This
means that the program must anticipate possible errors and respond to them if
they occur.</p>
</ans>
</question>

   
<question>
<ques><p>Why do programming languages
require that variables be declared before they are used? What does this have to
do with correctness and robustness?</p>
</ques>
<ans><p>It's a little inconvenient to
have to declare every variable before it is used, but it's much safer. If the
compiler would accept undeclared variables, then it would also accept
misspelled names and treat them as valid variables. This can easily lead to
incorrect programs. When variables must be declared, the unintentional creation
of a variable is simply impossible, and a whole class of possible bugs is
avoided.</p>
</ans>
</question>

   
<question>
<ques><p>What is a <i>precondition</i>? Give an example.</p>
</ques>
<ans><p>A precondition is a condition
that has to hold at a given point in the execution of a program, if the execution
of the program is to continue correctly. For example, the statement 
"<code>x&nbsp;=&nbsp;A[i];</code>" has two preconditions: that <code>A</code> is not <code>null</code> and
that <code>0&nbsp;&lt;=&nbsp;i &lt;&nbsp;A.length</code>. If either of these
preconditions is violated, then the execution of the statement will generate an
error.</p>
<p>Also, a precondition of a subroutine is a condition that has to be true when
the subroutine is called in order for the subroutine to work correctly.</p></ans>
</question>

   
<question>
<ques><p>Explain how preconditions
can be used as an aid in writing correct programs.</p>
</ques>
<ans><p>Suppose that a programmer
recognizes a precondition at some point in a program. This is a signal to the
programmer that an error might occur if the precondition is not met. In order to
have a correct and robust program, the programmer must deal with the possible
error. There are several approaches that the programmer can take. One approach
is to use an <code>if</code> statement to test whether the precondition is
satisfied. If not, the programmer can take some other action such as printing
an error message and terminating the program. Another approach is to use a
<code>try</code> statement to catch and respond to the error. This is really just a
cleaner way of accomplishing the same thing as the first approach. The best
approach, when it is possible, is to ensure that the precondition is satisfied
as a result of what has already been done in the program. For example, if the
precondition is that <code>x&nbsp;&gt;=&nbsp;0</code>, and the preceding statement
is "<code>x&nbsp;=&nbsp;Math.abs(y);</code>", then we know that the precondition is
satisfied, since the absolute value of any number is greater than or equal to
zero.</p>
</ans>
</question>

   
<question>
<ques><p>Java has a predefined class
called <classname>Throwable</classname>. What does this class represent? Why does it
exist?</p>
</ques>
<ans><p>The class <classname>Throwable</classname>
represents all possible objects that can be thrown by a <code>throw</code>
statement and caught by a <code>catch</code> clause in a <code>try..catch</code>
statement. That is, the thrown object must belong to the class
<classname>Throwable</classname> or to one of its (many) subclasses such as
<classname>Exception</classname> and <classname>RuntimeException</classname>. The object carries
information about an exception from the point where the exception occurs to the
point where it is caught and handled.</p>
</ans>
</question>

   
<question>
<ques><p>Write a method that
prints out a <code>3N+1</code> sequence starting from a given integer, <code>N</code>.
The starting value should be a parameter to the method. If the parameter is
less than or equal to zero, throw an <classname>IllegalArgumentException</classname>. If the
number in the sequence becomes too large to be represented as a value of type
<ptype>int</ptype>, throw an <classname>ArithmeticException</classname>.</p>
</ques>
<ans><p>The problem of large values in a
<code>3N+1</code> sequence was discussed in <localref href="robustness.1"/>. In
that section, it is pointed out that the test "<code>if&nbsp;(N&nbsp;&gt;&nbsp;2147483646/3)</code>" 
can be used to test whether the value of <code>N</code> has
become too large. This test is used in the following method.</p>

<pre>/** Print the 3N+1 sequence starting from N.  If N
 * is not greater than 0 or if the value of N exceeds
 * the maximum legal value for ints, than an
 * exception will be thrown.
 */
static void printThreeNSequence(int N) {
   if (N &lt; 1) {
      throw new IllegalArgumentException(
                  "Starting value for 3N+1 sequence must be &gt; 0.");
   }
   System.out.println("3N+1 sequence starting from " + N + " is: ");
   System.out.println(N);
   while (N &gt; 1) {
      if (N % 2 == 0) {  // N is even.  Divide by 2.
          N = N / 2;
      }
      else {  // N is odd.  Multiply by 3 and add 1.
          if (N &gt; 2147483646/3) {
             throw new ArithmeticException("Value has exceeded the largest int.");
          }
          N = 3 * N + 1;
      }
      System.out.println(N);
   }
}</pre>

<p>(Note that it would be possible to declare that this routine can throw
exceptions by adding a "throws" clause to the heading:</p>

<pre>static void printThreeNSequence(int N)
           throws IllegalArgumentException, ArithmeticException {</pre>

<p>However, this is not required since <code>IllegalArgumentExceptions</code> and
<code>ArithmeticExceptions</code> are not checked exceptions.)</p>
</ans>
</question>

   
<question>
<ques><p>Rewrite the method from the previous question, using <code>assert</code>
statements instead of exceptions to check for errors.  What is the difference between
the two versions of the method when the program is run?</p>
</ques>
<ans><p>We can replace the <code>if</code> statements that check for errors with
assert statements that give the same error messages:</p>

<pre>/** Print the 3N+1 sequence starting from N.
  * Precondition:  N &gt; 0 and the 3N+1 sequence for N does not contain
  * any numbers that are too big to be represented as 32-bit ints.
  */
static void printThreeNSequence(int N) {
   
   assert  N &gt; 0 : "Starting value for 3N+1 sequence must be &gt; 0.";

   System.out.println("3N+1 sequence starting from " + N + " is: ");
   
   System.out.println(N);
   while (N &gt; 1) {
      if (N % 2 == 0) {  // N is even.  Divide by 2.
          N = N / 2;
      }
      else {  // N is odd.  Multiply by 3 and add 1.
          assert  N &lt;= 2147483646/3 : "Value has exceeded the largest int.";
          N = 3 * N + 1;
      }
      System.out.println(N);
   }
   
}</pre>
   
<p>The first version of the method will always check for errors when the program
is run.  The second version, on the other hand, does not actually do any error checking
when the program is run in the ordinary way.  In order for <code>assert</code> statements
to be executed, the program must be run with assertions enabled.  The <code>assert</code>
statements are really there only to do error-checking during debugging and testing.
(In this particular case, I would say that an exception should definitely be thrown when
<code>N</code> exceeds the maximum legal value, but that it's reasonable to use
an <code>assert</code> to check whether <code>N&nbsp;&gt;&nbsp;0</code>.)</p>
</ans>
</question>

   
<question>
<ques><p>Some classes of exceptions are <i>checked exceptions</i> that
require <i>mandatory exception handling.</i> Explain what this means.</p>
</ques>
<ans><p>Subclasses of the class
<classname>Exception</classname> which are not subclasses of <classname>RuntimeException</classname>
are checked exceptions. This has two consequences: First, if a
method can throw such an exception, then it must declare this fact by
adding a <code>throws</code> clause to the method heading. Second, if a routine
includes any code that can generate such an exception, then the routine must
deal with the exception. It can do this by including the code in a <code>try</code>
statement that has a <code>catch</code> clause to handle the exception. Or it can
add a <code>throws</code> clause to the method definition to declare that calling 
the method might throw the exception.</p>
</ans>
</question>

   
<question>
<ques><p>Consider a subroutine <code>processData()</code> that has the header</p>

<pre>static void processData() throws IOException</pre>

<np>Write a <code>try..catch</code> statement that calls this subroutine and prints
an error message if an <classname>IOException</classname> occurs.</np>
</ques>
<ans>
<pre>try {
   processData();
}
catch (IOException e) {
   System.out.println("An IOException occurred while processing the data.");
}</pre>
</ans>
</question>

   
<question>
<ques><p>Why should a subroutine
throw an exception when it encounters an error? Why not just terminate the
program?</p>
</ques>
<ans><p>Terminating the program is too
drastic, and this tactic certainly doesn't lead to robust programs! It's likely
that the subroutine doesn't know what to do with the error, but that doesn't
mean that it should abort the whole program. When the subroutine throws an
exception, the subroutine is terminated, but the program that called the
subroutine still has a chance to catch the exception and handle it. In effect,
the subroutine is saying "Alright, I'm giving up. Let's hope someone else can
deal with the problem."</p>
</ans>
</question>

<question>
<ques><p>Suppose that you have a choice of two algorithms that perform
the same task.  One has average-case run time that is &Theta;(n<sup>2</sup>) while the run time
of the second algorithm has an average-case run time that is &Theta;(n*log(n)).  Suppose that
you need to process an input of size n&nbsp;=&nbsp;100.  Which algorithm would
you choose?  Can you be certain that you are choosing the fastest algorithm for the
input that you intend to process.
</p></ques>
<ans><p>In the absence of other information, the second algorithm, with run time
&Theta;(n*log(n)), is the better choice, since n*log(n) is much smaller than n<sup>2</sup>,
for most values of n.
However, it's not completely certain that the second algorithm is the better choice in
a particular case.  First of all, although the n*log(n) algorithm is certainly better
than the n<sup>2</sup> algorithm for large enough values of n, that is not necessarily
true for n&nbsp;=&nbsp;100.  Second, there is the issue of "average-case" run time.
Even if the n*log(n) algorithm is better for most inputs of size 100, it might not 
be better for all such inputs.
</p></ans>
</question>

<question>
<ques><p>Analyze the run time of the following algorithm.  That is, find a function
f(n) such that the run time of the algorithm is &BigOh;(f(n)) or, better, &Theta;(f(n)).
Assume that <code>A</code> is an array of integers, and use the length of the array
as the input size, n.
</p>
<pre>
int total = 0;
for (int i = 0; i &lt; A.length; i++) {
   if (A[i] &gt; 0)
      total = total + A[i];
}
</pre>
</ques>
<ans><p>The run time of this algorithm is &Theta;(n).  There are several things in the
code that are evaluated n times:  the test "i&nbsp;&lt;&nbsp;A.length", the increment
"i++", and the test in the if statement.  The initialization is done once, and
nothing is executed more than n times.  It follows that both the worst-case and
the average case run times are &Theta;(n).</p></ans>
</question>

</quiz>